apiVersion: apps/v1
kind: Deployment
metadata:
#  annotations:
#    deployment.kubernetes.io/revision: "1"
#  creationTimestamp: "2021-10-29T03:39:16Z"
#  generation: 1
  labels:
    app: zaldi-api
  name: zaldi-api
  namespace: zaldii
#  resourceVersion: "6677348"
#  uid: 38718923-56cb-45b8-8dff-d15f73d45538
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zaldi-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zaldi-api
    spec:
      containers:
      - image: acronboarding.azurecr.io/zaldi_api
        imagePullPolicy: Always
        name: zaldi-api
        env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: sql-server-zaldi
                key: api-db
          - name: AuthorizationServer__Address
            valueFrom:
              configMapKeyRef:
                name: config-zaldi
                key: AuthorizationServerAddress
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
#status:
#  availableReplicas: 1
#  conditions:
#  - lastTransitionTime: "2021-10-29T03:39:21Z"
#    lastUpdateTime: "2021-10-29T03:39:21Z"
#    message: Deployment has minimum availability.
#    reason: MinimumReplicasAvailable
#    status: "True"
#    type: Available
#  - lastTransitionTime: "2021-10-29T03:39:16Z"
#    lastUpdateTime: "2021-10-29T03:39:21Z"
#    message: ReplicaSet "api-6bfd7bc669" has successfully progressed.
#    reason: NewReplicaSetAvailable
#    status: "True"
#    type: Progressing
#  observedGeneration: 1
#  readyReplicas: 1
#  replicas: 1
#  updatedReplicas: 1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zaldi-api
  name: zaldi-api
spec:
  ports:
  - name: zaldi-port
    port: 80
  type: LoadBalancer
  selector:
    app: zaldi-api
status:
  loadBalancer: {}