apiVersion: v1
kind: Secret
metadata:
  name: sql-server-zaldi
data:
  auth-db: U2VydmVyPXRjcDpvbi1ib2FyZC1hc3RyYS1zdGFyLmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPXphbGRpLWF1dGgtZGI7UGVyc2lzdCBTZWN1cml0eSBJbmZvPUZhbHNlO1VzZXIgSUQ9YWRtaW5hZG1pbjtQYXNzd29yZD1FY29tUEBzc3cwcmQ7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPUZhbHNlO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=
  api-db: U2VydmVyPXRjcDpvbi1ib2FyZC1hc3RyYS1zdGFyLmRhdGFiYXNlLndpbmRvd3MubmV0LDE0MzM7SW5pdGlhbCBDYXRhbG9nPXphbGRpLWRiO1BlcnNpc3QgU2VjdXJpdHkgSW5mbz1GYWxzZTtVc2VyIElEPWFkbWluYWRtaW47UGFzc3dvcmQ9RWNvbVBAc3N3MHJkO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz1GYWxzZTtFbmNyeXB0PVRydWU7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1GYWxzZTtDb25uZWN0aW9uIFRpbWVvdXQ9MzA7