apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-10-29T07:46:29Z"
  generation: 1
  labels:
    app: zaldi-auth
  name: zaldi-auth
  namespace: zaldii
  resourceVersion: "6699354"
  uid: e2d4bb59-4a4d-4aa2-b84e-78b7be7a9de4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zaldi-auth
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zaldi-auth
    spec:
      containers:
      - image: acronboarding.azurecr.io/zaldi_auth_fix
        imagePullPolicy: Always
        name: zaldi-auth-fix-m9jgd
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-10-29T07:46:31Z"
    lastUpdateTime: "2021-10-29T07:46:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-10-29T07:46:29Z"
    lastUpdateTime: "2021-10-29T07:46:31Z"
    message: ReplicaSet "zaldi-auth-f6f4bd6d6" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
